/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  safelist: [
    // Classes generated dynamically in app.js template literals (not statically analysable)
    'glass-nav',
    'shadow-sm',
    'font-display',
    'font-bold',
    'font-semibold',
    'text-brand-slate',
    'text-brand-orange',
    'text-brand-muted',
    'bg-brand-warm',
    'bg-brand-slate',
    'bg-brand-orange',
    'border-brand-light',
    'border-brand-orange',
    'text-orange-100',
    'bg-slate-50',
    'bg-orange-50',
    'rounded-2xl',
    'rounded-xl',
    'rounded-full',
    'rounded-lg',
    'p-4',
    'p-3',
    'space-y-2',
    'flex',
    'items-center',
    'justify-between',
    'text-xs',
    'text-sm',
    'text-[10px]',
    'text-[11px]',
    'px-2',
    'px-3',
    'py-1',
    'py-0.5',
    'gap-2',
    'gap-3',
    'border',
    'border-slate-100',
    'border-dashed',
    'border-slate-200',
    'text-red-500',
    'hover:text-red-700',
    'shadow-soft',
    'translate-x-full',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
      colors: {
        brand: {
          orange: '#F97316',
          hover: '#EA580C',
          amber: '#F59E0B',
          warm: '#FFF7ED',
          light: '#FFEDD5',
          slate: '#0F172A',
          muted: '#475569',
          bg: '#FAFAFA',
        },
      },
      boxShadow: {
        soft: '0px 10px 30px rgba(249, 115, 22, 0.08)',
        'hover-lift': '0px 20px 40px rgba(249, 115, 22, 0.15)',
        modal: '0px 25px 50px -12px rgba(15, 23, 42, 0.25)',
      },
      animation: {
        blob: 'blob 7s infinite',
        float: 'float 5s ease-in-out infinite',
      },
      keyframes: {
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(25px, -30px) scale(1.05)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.95)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
};
